[package]
name = "gsettings-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
heck = "0.4.0"
quick-xml = { version = "0.22.0", features = ["serialize"] }
serde = { version = "1.0.137", features = ["derive"] }
typetag = "0.1.8"
