[package]
name = "gsettings-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_xml = { package = "serde-xml-rs", version = "0.5.1" }
serde = { version = "1.0.137", features = ["derive"] }
anyhow = "1.0.57"
heck = "0.4.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
typetag = "0.1.8"
